### ISSUE TITLE
尝试构建失败

### ISSUE THREAD

**Issue by 2ndElemet** [niuhuan/pikapi-flutter#36]
> 使用gomobile 执行 `gomobile bind -target=android/arm -o lib/Pikapi.aar ./`
> 后运行 `flutter build apk` 时报错 
运行环境为windows10

如下
![image](https://user-images.githubusercontent.com/72551339/135653220-3385f372-1916-4880-8b35-5bc98446cb2b.png)
```
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.base/java.net.PlainSocketImpl.connect0(Native Method)
        at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/java.net.Socket.connect(Socket.java:558)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
        at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:212)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1208)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleRelease'...                           43.2s
Gradle task assembleRelease failed with exit code 1
```

**Comment by 2ndElemet** [comment]
对 golang flutter 不熟悉,希望 能进行一下apk构建 放出 release

**Comment by niuhuan** [comment]
安卓依赖等下载失败，请设置代理。以前层放出过release，现在服务器负载过大所以取消了release请求，感谢您的Star，也可以留下您的联系方式（邮箱，QQ等，我会发送APK过去）

**Comment by 2ndElemet** [comment]
QQ: 2781372804
Mail: 2781372804@qq.com
非常感谢您的回复

**Comment by zhongfly** [comment]
Tips: From 1.16, it is recommended to execute go get -d golang.org/x/mobile/cmd/gomobile before each execution of gomobile bind .... go get will automatically add indirect references to go.mod. These indirect references maybe automatically deleted by ide or go mod tidy, but they are required!
应该修改下readme…我感觉流程不完善

**Comment by niuhuan** [comment]
> Tips: From 1.16, it is recommended to execute `go get -d golang.org/x/mobile/cmd/gomobile` before each execution of `gomobile bind ....` go get will automatically add indirect references to go.mod. These indirect references maybe automatically deleted by ide or go mod tidy, but they are required! 应该修改下readme…我感觉流程不完善

我这里并没有什么问题，另外gomobile是全局的，不需要在有gomod的文件中执行

go install golang.org/x/mobile/cmd/gomobile@latest
go get golang.org/x/mobile/cmd/gobind

**Comment by aaaly666** [comment]
> 安卓依赖等下载失败，请设置代理。以前层放出过release，现在服务器负载过大所以取消了release请求，感谢您的Star，也可以留下您的联系方式（邮箱，QQ等，我会发送APK过去）

因为我不会编译家里也没有电脑，可以发给我apk吗，我的联系方式QQ:1640954520

**Comment by Z-fly** [comment]
> 安卓依赖等下载失败，请设置代理。以前层放出过release，现在服务器负载过大所以取消了release请求，感谢您的Star，也可以留下您的联系方式（邮箱，QQ等，我会发送APK过去）

服务器负载过大，果然还是那个原因吗

**Comment by niuhuan** [comment]
> > 安卓依赖等下载失败，请设置代理。以前层放出过release，现在服务器负载过大所以取消了release请求，感谢您的Star，也可以留下您的联系方式（邮箱，QQ等，我会发送APK过去）
> 
> 服务器负载过大，果然还是那个原因吗

我只是觉得 两个月 3500 DL 他们会少挣好多钱，一个平台还是要活下去的，我无非是想要点赞。

**Comment by zhongfly** [comment]
> > 安卓依赖等下载失败，请设置代理。以前层放出过release，现在服务器负载过大所以取消了release请求，感谢您的Star，也可以留下您的联系方式（邮箱，QQ等，我会发送APK过去）
> 
> 服务器负载过大，果然还是那个原因吗

这也不能完全说是这导致的，之前他们也经常出现。很多人也不过是从官方客户端换成了这个，实际压力不见得明显增加了。

**Comment by Z-fly** [comment]
我觉得可以在这里后台模拟加载广告的请求，这样他们也有钱挣，我们舆论压力也小一些

**Comment by zhongfly** [comment]
> 我觉得可以在这里后台模拟加载广告的请求，这样他们也有钱挣，我们舆论压力也小一些

“舆论压力”本来就不大，大部分哔咔用户都不知道这个项目，使用这个项目的用官方客户端多半也不愿意点击广告的…所以用户是不太在意这些的
主要是哔咔方面不愿意第三方客户端分流它的流量…

**Comment by Z-fly** [comment]
我是建议niuhuan打开discussion吧，
我上次谈论这个的issue直接被niuhuan删掉了。

**Comment by Z-fly** [comment]
官方明显不愿意分流啊，给很多仓库发函了。

**Comment by niuhuan** [comment]
> 我是建议niuhuan打开discussion吧， 我上次谈论这个的issue直接被niuhuan删掉了。

删帖是因为github的搜索引擎，可以搜issues而已，只想慢慢发展。

而且大部分用户下载了就没音信了，没有star和issues，勤劳的鸟儿有虫吃。

**Comment by niuhuan** [comment]
> 官方明显不愿意分流啊，给很多仓库发函了。

CDN很贵的，而且官方技术槽点很多，管理和USER用一个端，浏览下载也没鉴权，甚至评论不能删除，管理员也只能屏蔽。

改API意味着所有用户必须更新，成本极大。
